// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NInput: typeof import('naive-ui')['NInput']
    NP: typeof import('naive-ui')['NP']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    PdfEditor: typeof import('./src/components/PdfEditor.vue')['default']
    PdfPage: typeof import('./src/components/PdfPage.vue')['default']
    TheBottomBar: typeof import('./src/components/TheBottomBar.vue')['default']
    TheFileUploadOverlay: typeof import('./src/components/TheFileUploadOverlay.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
  }
}
